/**
 * Landing Page
 */

export const APP_SET_TOOLBAR_STATE = 'APP_SET_TOOLBAR_STATE';
export const APP_TOOLBAR_SHOW_BACKPAGE = 'APP_TOOLBAR_SHOW_BACKPAGE';
export const APP_SET_CURTAIN_STATE = 'APP_SET_CURTAIN_STATE';

export const SUBMIT_LANDING_PAGE_REGISTRATION_FORM =
  'SUBMIT_LANDING_PAGE_REGISTRATION_FORM';
export const LANDING_PAGE_REGISTRATION_FORM_START =
  'LANDING_PAGE_REGISTRATION_FORM_START';
export const LANDING_PAGE_REGISTRATION_FORM_SUCCESS =
  'LANDING_PAGE_REGISTRATION_FORM_SUCCESS';
export const LANDING_PAGE_REGISTRATION_FORM_FAIL =
  'LANDING_PAGE_REGISTRATION_FORM_FAIL';

export const GET_TRENDING_CATEGORIES = 'GET_TRENDING_CATEGORIES';
export const SET_TRENDING_CATEGORIES = 'SET_TRENDING_CATEGORIES';

export const GET_PAYMENT_METHOD = 'GET_PAYMENT_METHOD';
export const SET_PAYMENT_METHOD = 'SET_PAYMENT_METHOD';
export const GET_SHIPPING_METHOD = 'GET_SHIPPING_METHOD';
export const SET_SHIPPING_METHOD = 'SET_SHIPPING_METHOD';

export const SUBMIT_FORGOT_PASSWORD_START = 'SUBMIT_FORGOT_PASSWORD_START';
export const SUBMIT_FORGOT_PASSWORD_SUCCESS = 'SUBMIT_FORGOT_PASSWORD_SUCCESS';
export const SUBMIT_FORGOT_PASSWORD_FAIL = 'SUBMIT_FORGOT_PASSWORD_FAIL';
export const SUBMIT_RESET_PASSWORD_START = 'SUBMIT_RESET_PASSWORD_START';
export const SUBMIT_RESET_PASSWORD_SUCCESS = 'SUBMIT_RESET_PASSWORD_SUCCESS';
export const SUBMIT_RESET_PASSWORD_FAIL = 'SUBMIT_RESET_PASSWORD_FAIL';
export const RESET_PASSWORD_STORE = 'RESET_PASSWORD_STORE';

export const DOWNLOAD_CATALOG_FORM = 'DOWNLOAD_CATALOG_FORM';
export const DOWNLOAD_CATALOG_FORM_START = 'DOWNLOAD_CATALOG_FORM_START';
export const DOWNLOAD_CATALOG_FORM_SUCCESS = 'DOWNLOAD_CATALOG_FORM_SUCCESS';
export const DOWNLOAD_CATALOG_FORM_FAIL = 'DOWNLOAD_CATALOG_FORM_FAIL';

export const SUBMIT_REGISTRATION_MEMBER_NON_RESELLER_FORM =
  'SUBMIT_REGISTRATION_MEMBER_NON_RESELLER_FORM';
export const REGISTRATION_MEMBER_NON_RESELLER_START =
  'REGISTRATION_MEMBER_NON_RESELLER_START';
export const REGISTRATION_MEMBER_NON_RESELLER_SUCCESS =
  'REGISTRATION_MEMBER_NON_RESELLER_SUCCESS';
export const REGISTRATION_MEMBER_NON_RESELLER_FAIL =
  'REGISTRATION_MEMBER_NON_RESELLER_FAIL';

export const CHECK_REFERRAL_CODE_START = 'CHECK_REFERRAL_CODE_START';
export const CHECK_REFERRAL_CODE_SUCCESS = 'CHECK_REFERRAL_CODE_SUCCESS';
export const CHECK_REFERRAL_CODE_FAIL = 'CHECK_REFERRAL_CODE_FAIL';

export const REGISTRATION_RESELLER_STORE = 'REGISTRATION_RESELLER_STORE';
export const STORE_REGISTRATION_SIMPLE_FORM = 'STORE_REGISTRATION_SIMPLE_FORM';
export const STORE_REGISTRATION_STEP1 = 'STORE_REGISTRATION_STEP1';
export const STORE_REGISTRATION_STEP2 = 'STORE_REGISTRATION_STEP2';
export const STORE_REGISTRATION_STEP3 = 'STORE_REGISTRATION_STEP3';

export const EDIT_PROFIL_START = 'EDIT_PROFIL_START';
export const EDIT_PROFIL_PHOTO_STORE = 'EDIT_PROFIL_PHOTO_STORE';
export const EDIT_PROFIL_SUCCESS = 'EDIT_PROFIL_SUCCESS';
export const EDIT_PROFIL_ERROR = 'EDIT_PROFIL_ERROR';
export const EDIT_PROFIL_STORE = 'EDIT_PROFIL_STORE';
export const EDIT_PROFIL_RESET = 'EDIT_PROFIL_RESET';
export const EDIT_PROFIL_RESET_LOADING = 'EDIT_PROFIL_RESET_LOADING';

export const EDIT_TOKO_START = 'EDIT_TOKO_START';
export const EDIT_TOKO_SUCCESS = 'EDIT_TOKO_SUCCESS';
export const EDIT_TOKO_ERROR = 'EDIT_TOKO_ERROR';
export const EDIT_TOKO_STORE = 'EDIT_TOKO_STORE';
export const EDIT_TOKO_RESET = 'EDIT_TOKO_RESET';
export const EDIT_TOKO_PROFIL_START = 'EDIT_TOKO_PROFIL_START';
export const EDIT_TOKO_PROFIL_SUCCESS = 'EDIT_TOKO_PROFIL_SUCCESS';
export const EDIT_TOKO_PROFIL_ERROR = 'EDIT_TOKO_PROFIL_ERROR';
export const STORE_DETAIL_PROFIL = 'STORE_DETAIL_PROFIL';
export const UPDATE_PROFIL_TOKO_START = 'UPDATE_PROFIL_TOKO_START';
export const UPDATE_PROFIL_TOKO_ERROR = 'UPDATE_PROFIL_TOKO_ERROR';
export const UPDATE_PHOTO_STORE = 'UPDATE_PHOTO_STORE';
export const STORE_GET_LIST_BANK = 'STORE_GET_LIST_BANK';

export const STORE_UPGRADE_MEMBER = 'STORE_UPGRADE_MEMBER';
export const STORE_SEARCH_PRODUCT_STOCK_ADJUSMENT = 'STORE_SEARCH_PRODUCT_STOCK_ADJUSMENT';

export const GET_TDS_PROVINCE_SUCCESS = 'GET_TDS_PROVINCE_SUCCESS';
export const GET_TDS_PROVINCE_START = 'GET_TDS_PROVINCE_START';

export const STORE_RENEWAL_TOP = 'STORE_RENEWAL_TOP';
export const STORE_RENEWAL_TOP_RESET = 'STORE_RENEWAL_TOP_RESET';

export const STORE_GET_REVIEW_TDS = 'STORE_GET_REVIEW_TDS';
export const STORE_ADD_REVIEW_TDS = 'STORE_ADD_REVIEW_TDS';
export const RESET_REVIEW_TDS = 'RESET_REVIEW_TDS';
export const STORE_RENEWALBY_POIN = 'STORE_RENEWALBY_POIN';
export const RENEWAL_SUCCESS_RESET = 'RENEWAL_SUCCESS_RESET';
export const STORE_GET_SALDO_MEMBER = 'STORE_GET_SALDO_MEMBER';
export const START_SEARCH_SALDO_DETAIL = 'START_SEARCH_SALDO_DETAIL';
export const STORE_SEARCH_SALDO_DETAIL = 'STORE_SEARCH_SALDO_DETAIL';
export const STORE_REQUEST_TARIK_SALDO = 'STORE_REQUEST_TARIK_SALDO';
export const STORE_GET_SALDO_MEMBER_OUT = 'STORE_GET_SALDO_MEMBER_OUT';
export const STORE_SEARCH_WITHDRAW_SALDO_DETAIL =
  'STORE_SEARCH_WITHDRAW_SALDO_DETAIL';
export const START_SEARCH_WITHDRAW_SALDO_DETAIL =
  'START_SEARCH_WITHDRAW_SALDO_DETAIL';
export const STORE_REQUEST_TARIK_SALDO_RESET =
  'STORE_REQUEST_TARIK_SALDO_RESET';
export const SALDO_STORE = 'SALDO_STORE';

export const GET_TDS_NEARBY_START = 'GET_TDS_NEARBY_START';
export const GET_TDS_NEARBY_SUCCESS = 'GET_TDS_NEARBY_SUCCESS';
export const GET_TDS_NEARBY_RESET = 'GET_TDS_NEARBY_RESET';
export const SEARCH_TDS = 'SEARCH_TDS';

export const ARTICLE_STORE = 'ARTICLE_STORE';
export const GET_LIST_ARTICLES_START = 'GET_LIST_ARTICLES_START';
export const GET_LIST_ARTICLES_SUCCESS = 'GET_LIST_ARTICLES_SUCCESS';
export const URL_GET_ARTICLE = 'GET_DETAIL_ARTICLE';
export const GET_ARTICLES_RESET = 'GET_ARTICLES_RESET';
export const ARTICLE_CATEGORY_STORE = 'ARTICLE_CATEGORY_STORE';
export const STORE_DETAIL_ARTICLE = 'STORE_DETAIL_ARTICLE';

export const GET_COMMENT_ARTICLE_START = 'GET_COMMENT_ARTICLE_START';
export const GET_COMMENT_ARTICLE_SUCCESS = 'GET_COMMENT_ARTICLE_SUCCESS';
export const SUBMIT_COMMENT_ARTICLE_START = 'SUBMIT_COMMENT_ARTICLE_START';
export const SUBMIT_COMMENT_ARTICLE_SUCCESS = 'SUBMIT_COMMENT_ARTICLE_SUCCESS';
export const STORE_COMMENT_ARTICLE = 'STORE_COMMENT_ARTICLE';

export const GET_DETAIL_ARTICLE_START = 'GET_DETAIL_ARTICLE_START';
export const GET_DETAIL_ARTICLE_SUCCESS = 'GET_DETAIL_ARTICLE_SUCCESS';
export const GET_LIST_ARTICLES_CARD_START = 'GET_LIST_ARTICLES_CARD_START';
export const GET_ARTICLE_CARD_SUCCESS = 'GET_ARTICLE_CARD_SUCCESS';
export const GET_ARTICLE_CARD_START = 'GET_ARTICLE_CARD_START';
export const CHECK_MEMBER_AKTIF_SUCCESS = 'CHECK_MEMBER_AKTIF_SUCCESS';
export const CHECK_MEMBER_AKTIF_START = 'CHECK_MEMBER_AKTIF_START';
export const CHECK_MEMBER_AKTIF_RESET = 'CHECK_MEMBER_AKTIF_RESET';

export const REPLY_REVIEW_TDS_STORE = 'REPLY_REVIEW_TDS_STORE';
export const PRODUCTS_SERUPA_START = 'PRODUCTS_SERUPA_START';
export const PRODUCTS_SERUPA_SUCCESS = 'PRODUCTS_SERUPA_SUCCESS';
export const PRODUCTS_SERUPA_FAIL = 'PRODUCTS_SERUPA_FAIL';

export const CHECK_MEMBER_AKTIFBY_EMAIL_SUCCESS =
  'CHECK_MEMBER_AKTIFBY_EMAIL_SUCCESS';
export const CHECK_MEMBER_AKTIFBY_EMAIL_START =
  'CHECK_MEMBER_AKTIFBY_EMAIL_START';
export const CHECK_MEMBER_AKTIFBY_EMAIL_RESET =
  'CHECK_MEMBER_AKTIFBY_EMAIL_RESET';
export const REQUEST_OPEN_STORE = 'REQUEST_OPEN_STORE';
export const STORE_UPDATE_VERIFICATION = 'STORE_UPDATE_VERIFICATION';
export const UPDATE_VERIFICATION_START = 'UPDATE_VERIFICATION_START';
export const UPDATE_VERIFICATION_SUCCESS = 'UPDATE_VERIFICATION_SUCCESS';
export const UPDATE_VERIFICATION_ERROR = 'UPDATE_VERIFICATION_ERROR';
export const UPDATE_VERIFICATION_RESET = 'UPDATE_VERIFICATION_RESET';
export const STORE_PHOTO_ID_CARD_NUMBER = 'STORE_PHOTO_ID_CARD_NUMBER';
export const DELETE_MEMBER_ADDRESS_SUCCESS = 'DELETE_MEMBER_ADDRESS_SUCCESS';

export const STORE_GET_CAREER = 'STORE_GET_CAREER';
export const DELETE_LIST_MEMBER_ADDRESS = 'DELETE_LIST_MEMBER_ADDRESS';
export const STORE_UPDATE_MEMBER_ADDRESS = 'STORE_UPDATE_MEMBER_ADDRESS';
export const UPDATE_MEMBER_ADDRESS_START = 'UPDATE_MEMBER_ADDRESS_START';
export const UPDATE_MEMBER_ADDRESS_SUCCESS = 'UPDATE_MEMBER_ADDRESS_SUCCESS';
export const UPDATE_MEMBER_ADDRESS_ERROR = 'UPDATE_MEMBER_ADDRESS_ERROR';
export const UPDATE_MEMBER_ADDRESS_RESET = 'UPDATE_MEMBER_ADDRESS_RESET';

export const EDIT_TOKO_POST_START = 'EDIT_TOKO_POST_START';
export const EDIT_TOKO_POST_SUCCESS = 'EDIT_TOKO_POST_SUCCESS';
export const EDIT_TOKO_POST_ERROR = 'EDIT_TOKO_POST_ERROR';
export const EDIT_TOKO_POST_RESET = 'EDIT_TOKO_POST_RESET';
export const EDIT_TOKO_STORE_NAME = 'EDIT_TOKO_STORE_NAME';
export const EDIT_TOKO_RESET_LOADING = 'EDIT_TOKO_RESET_LOADING';
export const TOKO_POST_STORE = 'TOKO_POST_STORE';

export const EDIT_TOKO_PROFIL_STORE = 'EDIT_TOKO_PROFIL_STORE';
export const EDIT_TOKO_PROFIL_START_IMAGE = 'EDIT_TOKO_PROFIL_START_IMAGE';
export const EDIT_TOKO_PROFIL_SUCCESS_IMAGE = 'EDIT_TOKO_PROFIL_SUCCESS_IMAGE';
export const EDIT_TOKO_PROFIL_ERROR_IMAGE = 'EDIT_TOKO_PROFIL_ERROR_IMAGE';
export const EDIT_TOKO_PROFIL_RESET = 'EDIT_TOKO_PROFIL_RESET';

export const STORE_PROFIL_ADD_BANK = 'STORE_PROFIL_ADD_BANK';
export const ADD_PROFIL_BANK_START = 'ADD_PROFIL_BANK_START';
export const ADD_PROFIL_BANK_SUCCESS = 'ADD_PROFIL_BANK_SUCCESS';
export const ADD_PROFIL_BANK_ERROR = 'ADD_PROFIL_BANK_ERROR';
export const ADD_PROFIL_BANK_RESET = 'ADD_PROFIL_BANK_RESET';

export const POST_UPDATE_STATUS_STORE = 'POST_UPDATE_STATUS_STORE';
export const STORE_UPDATE_STATUS = 'STORE_UPDATE_STATUS';

export const UPDATE_ADDRESS_START = 'UPDATE_ADDRESS_START';
export const UPDATE_ADDRESS_SUCCESS = 'UPDATE_ADDRESS_SUCCESS';
export const UPDATE_ADDRESS_ERROR = 'UPDATE_ADDRESS_ERROR';
export const UPDATE_ADDRESS_RESET = 'UPDATE_ADDRESS_RESET';
export const STORE_UPDATE_ADDRESS = 'STORE_UPDATE_ADDRESS';

export const UPDATE_BANK_START = 'UPDATE_BANK_START';
export const UPDATE_BANK_SUCCESS = 'UPDATE_BANK_SUCCESS';
export const UPDATE_BANK_ERROR = 'UPDATE_BANK_ERROR';
export const UPDATE_BANK_RESET = 'UPDATE_BANK_RESET';
export const STORE_UPDATE_BANK = 'STORE_UPDATE_BANK';

export const UPLOAD_PHOTO = 'UPLOAD_PHOTO';
export const ADD_ADDRESS_START = 'ADD_ADDRESS_START';
export const ADD_ADDRESS_SUCCESS = 'ADD_ADDRESS_SUCCESS';
export const ADD_ADDRESS_ERROR = 'ADD_ADDRESS_ERROR';
export const ADD_ADDRESS_RESET = 'ADD_ADDRESS_RESET';
export const STORE_ADD_ADDRESS = 'STORE_ADD_ADDRESS';

export const SET_DATA_CITY = 'SET_DATA_CITY';
export const GET_DATA_CITY = 'GET_DATA_CITY';
export const SET_DATA_PROVINCE = 'SET_DATA_PROVINCE';
export const GET_DATA_PROVINCE = 'GET_DATA_PROVINCE';
export const SET_DATA_DISTRICT = 'SET_DATA_DISTRICT';
export const GET_DATA_DISTRICT = 'GET_DATA_DISTRICT';

export const STORE_REGISTRATION_STEP4 = 'STORE_REGISTRATION_STEP4';
export const REGISTRATION_MEMBER_RESELLER_SUCCESS =
  'REGISTRATION_MEMBER_RESELLER_SUCCESS';
export const REGISTRATION_MEMBER_RESELLER_FAIL =
  'REGISTRATION_MEMBER_RESELLER_FAIL';
export const SUBMIT_REGISTRATION_MEMBER_RESELLER_FORM =
  'SUBMIT_REGISTRATION_MEMBER_RESELLER_FORM';
export const REGISTRATION_MEMBER_RESELLER_START =
  'REGISTRATION_MEMBER_RESELLER_START';
export const STATER_KIT_PRODUCTS_START = 'STATER_KIT_PRODUCTS_START';
export const STATER_KIT_PRODUCTS_SUCCESS = 'STATER_KIT_PRODUCTS_SUCCESS';

export const SUBMIT_LOGIN = 'SUBMIT_LOGIN';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const REMOVE_PRODUCTS = 'REMOVE_PRODUCTS';
export const PRODUCTS_START = 'PRODUCTS_START';
export const PRODUCTS_FAIL = 'PRODUCTS_FAIL';
export const STORE_CATEGORIES = 'STORE_CATEGORIES';
export const STORE_SEARCH_PRODUCTS = 'STORE_SEARCH_PRODUCTS';
export const START_SEARCH_PRODUCTS = 'START_SEARCH_PRODUCTS';
export const START_PRODUCT = 'START_PRODUCT';
export const STORE_PRODUCT = 'STORE_PRODUCT';
export const FAIL_PRODUCT = 'FAIL_PRODUCT';

export const GET_PROVINCES_START = 'GET_PROVINCES_START';
export const GET_PROVINCES_SUCCESS = 'GET_PROVINCES_SUCCESS';

export const GET_CITIES_START = 'GET_CITIES_START';
export const GET_CITIES_SUCCESS = 'GET_CITIES_SUCCESS';

export const GET_DISTRICTS_START = 'GET_DISTRICTS_START';
export const GET_DISTRICTS_SUCCESS = 'GET_DISTRICTS_SUCCESS';

export const GET_BRANCHES_START = 'GET_BRANCHES_START';
export const GET_BRANCHES_SUCCESS = 'GET_BRANCHES_SUCCESS';

export const GET_BRANCHES_NEARBY_START = 'GET_BRANCHES_NEARBY_START';
export const GET_BRANCHES_NEARBY_SUCCESS = 'GET_BRANCHES_NEARBY_SUCCESS';

export const GET_SHIPPING_COST_START = 'GET_SHIPPING_COST_START';
export const GET_SHIPPING_COST_SUCCESS = 'GET_SHIPPING_COST_SUCCESS';

export const GET_BRANCH_FREE_SHIPPING_START = 'GET_BRANCH_FREE_SHIPPING_START';
export const GET_BRANCH_FREE_SHIPPING_SUCCESS =
  'GET_BRANCH_FREE_SHIPPING_SUCCESS';

export const GET_DEFAULT_BRANCHES_FOR_AMBIL_SENDIRI_START =
  'GET_DEFAULT_BRANCHES_FOR_AMBIL_SENDIRI_START';
export const GET_DEFAULT_BRANCHES_FOR_AMBIL_SENDIRI_SUCCESS =
  'GET_DEFAULT_BRANCHES_FOR_AMBIL_SENDIRI_SUCCESS';
export const REMOVE_DEFAULT_BRANCHES_FOR_AMBIL_SENDIRI =
  'REMOVE_DEFAULT_BRANCHES_FOR_AMBIL_SENDIRI';

export const BRANCH_RECOMMENDATION_STORE = 'BRANCH_RECOMMENDATION_STORE';

export const WISHLIST_STORE = 'WISHLIST_STORE';
export const CART_ADD = 'CART_ADD';
export const CART_STORE = 'CART_STORE';

export const HOMEPAGE_STORE = 'HOMEPAGE_STORE';

export const PAYMENT_METHOD_STORE = 'PAYMENT_METHOD_STORE';
export const PAYMENT_CONFIRMATION_STORE = 'PAYMENT_CONFIRMATION_STORE';
export const PAYMENT_STORE = 'PAYMENT_STORE';

export const REVIEW_PRODUCT_STORE = 'REVIEW_PRODUCT_STORE';

export const TRANSACTION_STORE = 'TRANSACTION_STORE';
export const TRACKING_STORE = 'TRACKING_STORE';

export const REQUEST_TDS_STORE = 'REQUEST_TDS_STORE';
export const ADJUSTMENTS_STORE = 'ADJUSTMENTS_STORE';
export const STORE_STOCK_ADJUSMENT = 'STORE_STOCK_ADJUSMENT';
export const RESET_STORE_STOCK_ADJUSMENT = 'RESET_STORE_STOCK_ADJUSMENT';
export const ADJUSTMENTS_STORE_UPDATE = 'ADJUSTMENTS_STORE_UPDATE';
export const REDEEM_POINT_STORE = 'REDEEM_POINT_STORE';


export const REVIEW_TDS_STORE = 'REVIEW_TDS_STORE';

export const LANDING_PAGE_COUNT_NUMBER = 'LANDING_PAGE_COUNT_NUMBER';

export const UPLOAD_IMAGE_STORE = 'UPLOAD_IMAGE_STORE';

export const PURCHASE_PRODUCT_STORE = 'PURCHASE_PRODUCT_STORE';
export const ARTICLE_STORE_HOME_PAGE = 'ARTICLE_STORE_HOME_PAGE';
